# CycleSense

## Notebook 02: Data Cleaning

### Objective

The objective of this notebook is to clean the raw menstrual cycle dataset by identifying missing values, removing duplicate records, handling inconsistent data, eliminating irrelevant features, and preparing a clean dataset for exploratory data analysis and machine learning.

---

### Research Motivation

High-quality machine learning models depend on high-quality data. Before feature engineering or model training, the dataset must be carefully cleaned to minimize bias, reduce noise, and improve reproducibility.

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np
import pandas as pd

from src.data_loader import load_data

In [3]:
df = load_data()

df.shape

Dataset loaded successfully.
Shape: (1665, 80)

(1665, 80)

In [4]:
df_clean = df.copy()

In [5]:
duplicates = df_clean.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 12

In [6]:
if duplicates > 0:
    df_clean = df_clean.drop_duplicates()

print(df_clean.shape)

(1653, 80)

In [7]:
missing = (
    df_clean.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing.head(30)

ClientID                   0
CycleNumber                0
Group                      0
CycleWithPeakorNot         0
ReproductiveCategory       0
LengthofCycle              0
MeanCycleLength            0
EstimatedDayofOvulation    0
LengthofLutealPhase        0
FirstDayofHigh             0
TotalNumberofHighDays      0
TotalHighPostPeak          0
TotalNumberofPeakDays      0
TotalDaysofFertility       0
TotalFertilityFormula      0
LengthofMenses             0
MeanMensesLength           0
MensesScoreDayOne          0
MensesScoreDayTwo          0
MensesScoreDayThree        0
MensesScoreDayFour         0
MensesScoreDayFive         0
MensesScoreDaySix          0
MensesScoreDaySeven        0
MensesScoreDayEight        0
MensesScoreDayNine         0
MensesScoreDayTen          0
MensesScoreDay11           0
MensesScoreDay12           0
MensesScoreDay13           0
dtype: int64

In [8]:
missing_percent = (
    df_clean.isnull().mean() * 100
).sort_values(ascending=False)

missing_percent.head(30)

ClientID                   0.0
CycleNumber                0.0
Group                      0.0
CycleWithPeakorNot         0.0
ReproductiveCategory       0.0
LengthofCycle              0.0
MeanCycleLength            0.0
EstimatedDayofOvulation    0.0
LengthofLutealPhase        0.0
FirstDayofHigh             0.0
TotalNumberofHighDays      0.0
TotalHighPostPeak          0.0
TotalNumberofPeakDays      0.0
TotalDaysofFertility       0.0
TotalFertilityFormula      0.0
LengthofMenses             0.0
MeanMensesLength           0.0
MensesScoreDayOne          0.0
MensesScoreDayTwo          0.0
MensesScoreDayThree        0.0
MensesScoreDayFour         0.0
MensesScoreDayFive         0.0
MensesScoreDaySix          0.0
MensesScoreDaySeven        0.0
MensesScoreDayEight        0.0
MensesScoreDayNine         0.0
MensesScoreDayTen          0.0
MensesScoreDay11           0.0
MensesScoreDay12           0.0
MensesScoreDay13           0.0
dtype: float64

In [9]:
df_clean.columns.tolist()

['ClientID',
 'CycleNumber',
 'Group',
 'CycleWithPeakorNot',
 'ReproductiveCategory',
 'LengthofCycle',
 'MeanCycleLength',
 'EstimatedDayofOvulation',
 'LengthofLutealPhase',
 'FirstDayofHigh',
 'TotalNumberofHighDays',
 'TotalHighPostPeak',
 'TotalNumberofPeakDays',
 'TotalDaysofFertility',
 'TotalFertilityFormula',
 'LengthofMenses',
 'MeanMensesLength',
 'MensesScoreDayOne',
 'MensesScoreDayTwo',
 'MensesScoreDayThree',
 'MensesScoreDayFour',
 'MensesScoreDayFive',
 'MensesScoreDaySix',
 'MensesScoreDaySeven',
 'MensesScoreDayEight',
 'MensesScoreDayNine',
 'MensesScoreDayTen',
 'MensesScoreDay11',
 'MensesScoreDay12',
 'MensesScoreDay13',
 'MensesScoreDay14',
 'MensesScoreDay15',
 'TotalMensesScore',
 'MeanBleedingIntensity',
 'NumberofDaysofIntercourse',
 'IntercourseInFertileWindow',
 'UnusualBleeding',
 'PhasesBleeding',
 'IntercourseDuringUnusBleed',
 'Age',
 'AgeM',
 'Maristatus',
 'MaristatusM',
 'Yearsmarried',
 'Wedding',
 'Religion',
 'ReligionM',
 'Ethnicity',
 'EthnicityM',
 'Schoolyears',
 'SchoolyearsM',
 'OccupationM',
 'IncomeM',
 'Height',
 'Weight',
 'Reprocate',
 'Numberpreg',
 'Livingkids',
 'Miscarriages',
 'Abortions',
 'Medvits',
 'Medvitexplain',
 'Gynosurgeries',
 'LivingkidsM',
 'Boys',
 'Girls',
 'MedvitsM',
 'MedvitexplainM',
 'Urosurgeries',
 'Breastfeeding',
 'Method',
 'Prevmethod',
 'Methoddate',
 'Whychart',
 'Nextpreg',
 'NextpregM',
 'Spousesame',
 'SpousesameM',
 'Timeattemptpreg',
 'BMI']

In [11]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1653 entries, 0 to 1664
Data columns (total 80 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ClientID                    1653 non-null   object
 1   CycleNumber                 1653 non-null   int64
 2   Group                       1653 non-null   int64
 3   CycleWithPeakorNot          1653 non-null   int64
 4   ReproductiveCategory        1653 non-null   int64
 5   LengthofCycle               1653 non-null   int64
 6   MeanCycleLength             1653 non-null   object
 7   EstimatedDayofOvulation     1653 non-null   object
 8   LengthofLutealPhase         1653 non-null   object
 9   FirstDayofHigh              1653 non-null   object
 10  TotalNumberofHighDays       1653 non-null   object
 11  TotalHighPostPeak           1653 non-null   object
 12  TotalNumberofPeakDays       1653 non-null   object
 13  TotalDaysofFertility        1653 non-null   object
 14  TotalFertilityFormula       1653 non-null   object
 15  LengthofMenses              1653 non-null   object
 16  MeanMensesLength            1653 non-null   object
 17  MensesScoreDayOne           1653 non-null   object
 18  MensesScoreDayTwo           1653 non-null   object
 19  MensesScoreDayThree         1653 non-null   object
 20  MensesScoreDayFour          1653 non-null   object
 21  MensesScoreDayFive          1653 non-null   object
 22  MensesScoreDaySix           1653 non-null   object
 23  MensesScoreDaySeven         1653 non-null   object
 24  MensesScoreDayEight         1653 non-null   object
 25  MensesScoreDayNine          1653 non-null   object
 26  MensesScoreDayTen           1653 non-null   object
 27  MensesScoreDay11            1653 non-null   object
 28  MensesScoreDay12            1653 non-null   object
 29  MensesScoreDay13            1653 non-null   object
 30  MensesScoreDay14            1653 non-null   object
 31  MensesScoreDay15            1653 non-null   object
 32  TotalMensesScore            1653 non-null   object
 33  MeanBleedingIntensity       1653 non-null   object
 34  NumberofDaysofIntercourse   1653 non-null   object
 35  IntercourseInFertileWindow  1653 non-null   object
 36  UnusualBleeding             1653 non-null   object
 37  PhasesBleeding              1653 non-null   object
 38  IntercourseDuringUnusBleed  1653 non-null   object
 39  Age                         1653 non-null   object
 40  AgeM                        1653 non-null   object
 41  Maristatus                  1653 non-null   object
 42  MaristatusM                 1653 non-null   object
 43  Yearsmarried                1653 non-null   object
 44  Wedding                     1653 non-null   object
 45  Religion                    1653 non-null   object
 46  ReligionM                   1653 non-null   object
 47  Ethnicity                   1653 non-null   object
 48  EthnicityM                  1653 non-null   object
 49  Schoolyears                 1653 non-null   object
 50  SchoolyearsM                1653 non-null   object
 51  OccupationM                 1653 non-null   object
 52  IncomeM                     1653 non-null   object
 53  Height                      1653 non-null   object
 54  Weight                      1653 non-null   object
 55  Reprocate                   1653 non-null   object
 56  Numberpreg                  1653 non-null   object
 57  Livingkids                  1653 non-null   object
 58  Miscarriages                1653 non-null   object
 59  Abortions                   1653 non-null   object
 60  Medvits                     1653 non-null   object
 61  Medvitexplain               1653 non-null   object
 62  Gynosurgeries               1653 non-null   object
 63  LivingkidsM                 1653 non-null   object
 64  Boys                        1653 non-null   object
 65  Girls                       1653 non-null   object
 66  MedvitsM                    1653 non-null   object
 67  MedvitexplainM              1653 non-null   object
 68  Urosurgeries                1653 non-null   object
 69  Breastfeeding               1653 non-null   object
 70  Method                      1653 non-null   object
 71  Prevmethod                  1653 non-null   object
 72  Methoddate                  1653 non-null   object
 73  Whychart                    1653 non-null   object
 74  Nextpreg                    1653 non-null   object
 75  NextpregM                   1653 non-null   object
 76  Spousesame                  1653 non-null   object
 77  SpousesameM                 1653 non-null   object
 78  Timeattemptpreg             1653 non-null   object
 79  BMI                         1653 non-null   object
dtypes: int64(5), object(75)
memory usage: 1.0+ MB

In [12]:
df_clean.dtypes

ClientID                object
CycleNumber              int64
Group                    int64
CycleWithPeakorNot       int64
ReproductiveCategory     int64
                         ...
NextpregM               object
Spousesame              object
SpousesameM             object
Timeattemptpreg         object
BMI                     object
Length: 80, dtype: object

In [13]:
dtype_summary = pd.DataFrame({
    "Column": df_clean.columns,
    "Data Type": df_clean.dtypes.astype(str)
})

dtype_summary

                                    Column Data Type
ClientID                          ClientID    object
CycleNumber                    CycleNumber     int64
Group                                Group     int64
CycleWithPeakorNot      CycleWithPeakorNot     int64
ReproductiveCategory  ReproductiveCategory     int64
...                                    ...       ...
NextpregM                        NextpregM    object
Spousesame                      Spousesame    object
SpousesameM                    SpousesameM    object
Timeattemptpreg            Timeattemptpreg    object
BMI                                    BMI    object

[80 rows x 2 columns]

In [14]:
df_clean.dtypes.value_counts()

object    75
int64      5
Name: count, dtype: int64

In [15]:
object_columns = df_clean.select_dtypes(include="object").columns.tolist()

print(f"Number of object columns: {len(object_columns)}")

object_columns

Number of object columns: 75

['ClientID',
 'MeanCycleLength',
 'EstimatedDayofOvulation',
 'LengthofLutealPhase',
 'FirstDayofHigh',
 'TotalNumberofHighDays',
 'TotalHighPostPeak',
 'TotalNumberofPeakDays',
 'TotalDaysofFertility',
 'TotalFertilityFormula',
 'LengthofMenses',
 'MeanMensesLength',
 'MensesScoreDayOne',
 'MensesScoreDayTwo',
 'MensesScoreDayThree',
 'MensesScoreDayFour',
 'MensesScoreDayFive',
 'MensesScoreDaySix',
 'MensesScoreDaySeven',
 'MensesScoreDayEight',
 'MensesScoreDayNine',
 'MensesScoreDayTen',
 'MensesScoreDay11',
 'MensesScoreDay12',
 'MensesScoreDay13',
 'MensesScoreDay14',
 'MensesScoreDay15',
 'TotalMensesScore',
 'MeanBleedingIntensity',
 'NumberofDaysofIntercourse',
 'IntercourseInFertileWindow',
 'UnusualBleeding',
 'PhasesBleeding',
 'IntercourseDuringUnusBleed',
 'Age',
 'AgeM',
 'Maristatus',
 'MaristatusM',
 'Yearsmarried',
 'Wedding',
 'Religion',
 'ReligionM',
 'Ethnicity',
 'EthnicityM',
 'Schoolyears',
 'SchoolyearsM',
 'OccupationM',
 'IncomeM',
 'Height',
 'Weight',
 'Reprocate',
 'Numberpreg',
 'Livingkids',
 'Miscarriages',
 'Abortions',
 'Medvits',
 'Medvitexplain',
 'Gynosurgeries',
 'LivingkidsM',
 'Boys',
 'Girls',
 'MedvitsM',
 'MedvitexplainM',
 'Urosurgeries',
 'Breastfeeding',
 'Method',
 'Prevmethod',
 'Methoddate',
 'Whychart',
 'Nextpreg',
 'NextpregM',
 'Spousesame',
 'SpousesameM',
 'Timeattemptpreg',
 'BMI']

In [16]:
for col in object_columns:
    print("=" * 60)
    print(col)
    print(df_clean[col].unique()[:10])

============================================================
ClientID
['nfp8122' 'nfp8114' 'nfp8109' 'nfp8107' 'nfp8106' 'nfp8024' 'nfp8020'
 'nfp8026' 'nfp8030' 'nfp8031']
============================================================
MeanCycleLength
['27.33' ' ' '31' '26.33' '26.88' '25.33' '28.75' '25.88' '27.67' '26.75']
============================================================
EstimatedDayofOvulation
['17' '15' '16' '14' '18' '12' '19' ' ' '11' '13']
============================================================
LengthofLutealPhase
['12' '14' '11' '13' '10' ' ' '21' '9' '8' '4']
============================================================
FirstDayofHigh
['12' '13' ' ' '10' '9' '8' '14' '11' '16' '6']
============================================================
TotalNumberofHighDays
['5' '2' '1' '4' '7' '6' '3' '11' '13' '10']
============================================================
TotalHighPostPeak
['0' '1' '2' '5' '3' '4' '6' ' ' '7']
============================================================
TotalNumberofPeakDays
['2' '0' '3' '1' '4' ' ' '6' '5' '7' '12']
============================================================
TotalDaysofFertility
['9' '6' '5' '8' '11' '10' '7' '15' '13' '14']
============================================================
TotalFertilityFormula
['15' '13' '14' '12' '10' '11' '9' '16' '17' '24']
============================================================
LengthofMenses
['5' '4' '6' '7' '10' '3' '8' '2' '9' '11']
============================================================
MeanMensesLength
['4.49' ' ' '4.5' '6.67' '4.75' '4.33' '4.67' '5.31' '6' '5.63']
============================================================
MensesScoreDayOne
['3' '1' '2' ' ']
============================================================
MensesScoreDayTwo
['3' '2' '1' ' ']
============================================================
MensesScoreDayThree
['2' '3' '1' ' ']
============================================================
MensesScoreDayFour
['1' '2' '3' ' ']
============================================================
MensesScoreDayFive
['1' ' ' '2' '3']
============================================================
MensesScoreDaySix
[' ' '1' '2' '3']
============================================================
MensesScoreDaySeven
[' ' '1' '2' '3']
============================================================
MensesScoreDayEight
[' ' '1' '2']
============================================================
MensesScoreDayNine
[' ' '1' '2']
============================================================
MensesScoreDayTen
[' ' '1']
============================================================
MensesScoreDay11
[' ' '1' '2']
============================================================
MensesScoreDay12
[' ' '2']
============================================================
MensesScoreDay13
[' ' '2']
============================================================
MensesScoreDay14
[' ' '1']
============================================================
MensesScoreDay15
[' ' '1']
============================================================
TotalMensesScore
['10' '12' '11' '9' '8' '6' '7' '13' '14' '15']
============================================================
MeanBleedingIntensity
['9.04' ' ' '7.5' '12.33' '7.38' '6.67' '8.33' '9.88' '9.83' '11.69']
============================================================
NumberofDaysofIntercourse
['5' '6' '3' '4' '7' '8' '0' '2' '1' '10']
============================================================
IntercourseInFertileWindow
['1' '0' ' ']
============================================================
UnusualBleeding
['0' '1' ' ']
============================================================
PhasesBleeding
[' ' '1' '0' '3' '2']
============================================================
IntercourseDuringUnusBleed
[' ' '1' '0' '2']
============================================================
Age
['36' ' ' '39' '29' '26' '25' '23' '33' '30' '31']
============================================================
AgeM
['39' ' ' '36' '32' '25' '38' '34' '24' '42' '31']
============================================================
Maristatus
['0' ' ' '2' '1']
============================================================
MaristatusM
['0' ' ' '2' '3' '1']
============================================================
Yearsmarried
['10' ' ' '4' '8' '1' '3' '12' '0' '7' '5']
============================================================
Wedding
[' ' '92010' '72009' '62009' '52009' '92009' '112009']
============================================================
Religion
['0' ' ' '4' '1']
============================================================
ReligionM
['0' ' ' '4' '1']
============================================================
Ethnicity
['0' ' ' '5' '3' '1' '2']
============================================================
EthnicityM
['0' ' ' '5' '3' '4' '2']
============================================================
Schoolyears
['8' ' ' '9' '7' '6' '2']
============================================================
SchoolyearsM
['8' ' ' '9' '7' '1' '6' '5']
============================================================
OccupationM
['3' ' ' '0' '5' '4' '1' '6' '2']
============================================================
IncomeM
['5' ' ' '3' '4' '1' '2' '0']
============================================================
Height
['63' ' ' '68' '66' '71' '65' '67' '72' '69' '70']
============================================================
Weight
['120' ' ' '185' '180' '200' '150' '155' '137' '135' '136']
============================================================
Reprocate
['0' ' ' '1' '6' '5' '2' '9' '3']
============================================================
Numberpreg
['3' ' ' '2' '0' '1' '6' '5' '4' '7' '9']
============================================================
Livingkids
['3' ' ' '2' '0' '1' '5' '4' '6' '7' '8']
============================================================
Miscarriages
['0' ' ' '1' '2' '4' '3']
============================================================
Abortions
['0' ' ' '1' '2']
============================================================
Medvits
['0' ' ' '1']
============================================================
Medvitexplain
[' ' 'multi-vitamin' 'Armour Thyroid 90 mg daily for hypothyroidism'
 'Multivitamin, B12, Folic Acid' 'Multivitamin' 'Prenatal vitamin, B6'
 'Hydrochlorothiazide' 'Toprol XL, Cybalta, Synthroid'
 'Albuterol Inhaler, Pulmacort'
 'provigil (narcolepsy) and detrol (urine inconsistency)']
============================================================
Gynosurgeries
[' ' 'c-section 10/98, D&C to remove placenta during delivery 9/00'
 '1991 - removal of one ovary' '2 C-Sections, 2-26-03 and 11-30-05'
 'Cryo and Cervical Leep in 1993'
 'C-section May 29, 2003, c-section October 1, 2004' 'd&c 10/1996'
 'Ovarian Cyst Removal via Laparoscopy- April 08, Jan 28, 09; D&C Operation for molar pregnancy Jan 20,09'
 '1996 - D and C, and 2003 - D and C' '5 C-sections']
============================================================
LivingkidsM
[' ' '5' '2' '0' '4' '3' '6' '1' '8']
============================================================
Boys
[' ' '3' '2' '1' '5' '4']
============================================================
Girls
[' ' '2' '1' '3' '4']
============================================================
MedvitsM
['0' ' ' '1']
============================================================
MedvitexplainM
[' ' 'multi-vitamin, acid reducer' 'Multivitamin'
 'Detrol, Vytorin, and Nexium' 'Vytorin' 'daily vitamins, hypertension'
 'vitamin c and daily vitamins' 'multivitamin'
 'Vitamins, allergy medications, motrin' 'Centrum Multivitamins']
============================================================
Urosurgeries
[' ' 'colonoscopy 2007' '2003 testicular torsion-right testicle removed'
 'cystoscopy w/kidney stone removal - 2001']
============================================================
Breastfeeding
['0' ' ' '6' '2' '3' '4']
============================================================
Method
['9' ' ' '7' '4' '8' '0' '6' '10']
============================================================
Prevmethod
[' ' '0' '9' '4' '7' '1' '6' '2' '8']
============================================================
Methoddate
[' ' '22009' '112008' '72007' '32009' '82009' '12009' '72008' '42009'
 '102007']
============================================================
Whychart
['2' ' ' '6' '3' '4' '1']
============================================================
Nextpreg
['7' ' ' '3' '4' '0' '6' '5' '2']
============================================================
NextpregM
['7' ' ' '3' '4' '0' '6' '5' '2']
============================================================
Spousesame
['1' ' ' '2' '0']
============================================================
SpousesameM
['1' ' ' '0']
============================================================
Timeattemptpreg
['0' ' ']
============================================================
BMI
['21.254724111867' ' ' '28.1260813148789' '29.0495867768595'
 '27.8912914104344' '24.9585798816568' '25.7905325443787'
 '21.4548897304522' '22.4627218934911' '21.9485766758494']

In [17]:
df_clean.replace(r'^\s*$', np.nan, regex=True, inplace=True)

In [18]:
missing = pd.DataFrame({
    "Missing Values": df_clean.isnull().sum(),
    "Percentage": (df_clean.isnull().mean() * 100).round(2)
})

missing = missing.sort_values(
    "Percentage",
    ascending=False
)

missing.head(20)

                            Missing Values  Percentage
MensesScoreDay15                      1652       99.94
MensesScoreDay14                      1652       99.94
MensesScoreDay13                      1652       99.94
MensesScoreDay12                      1652       99.94
MensesScoreDay11                      1651       99.88
Urosurgeries                          1650       99.82
MensesScoreDayTen                     1647       99.64
Wedding                               1643       99.40
MensesScoreDayNine                    1627       98.43
Gynosurgeries                         1627       98.43
Prevmethod                            1624       98.25
Methoddate                            1621       98.06
Girls                                 1610       97.40
Boys                                  1606       97.16
MedvitexplainM                        1594       96.43
MensesScoreDayEight                   1585       95.89
LivingkidsM                           1573       95.16
IntercourseDuringUnusBleed            1571       95.04
Medvitexplain                         1550       93.77
PhasesBleeding                        1547       93.59

In [19]:
numeric_columns = [
    "MeanCycleLength",
    "EstimatedDayofOvulation",
    "LengthofLutealPhase",
    "FirstDayofHigh",
    "TotalNumberofHighDays",
    "TotalHighPostPeak",
    "TotalNumberofPeakDays",
    "TotalDaysofFertility",
    "TotalFertilityFormula",
    "LengthofMenses",
    "MeanMensesLength",
    "MensesScoreDayOne",
    "MensesScoreDayTwo",
    "MensesScoreDayThree",
    "MensesScoreDayFour",
    "MensesScoreDayFive",
    "MensesScoreDaySix",
    "MensesScoreDaySeven",
    "MensesScoreDayEight",
    "MensesScoreDayNine",
    "MensesScoreDayTen",
    "MensesScoreDay11",
    "MensesScoreDay12",
    "MensesScoreDay13",
    "MensesScoreDay14",
    "MensesScoreDay15",
    "TotalMensesScore",
    "MeanBleedingIntensity",
    "NumberofDaysofIntercourse",
    "IntercourseInFertileWindow",
    "UnusualBleeding",
    "PhasesBleeding",
    "IntercourseDuringUnusBleed",
    "Age",
    "AgeM",
    "Maristatus",
    "MaristatusM",
    "Yearsmarried",
    "Religion",
    "ReligionM",
    "Ethnicity",
    "EthnicityM",
    "Schoolyears",
    "SchoolyearsM",
    "OccupationM",
    "IncomeM",
    "Height",
    "Weight",
    "Reprocate",
    "Numberpreg",
    "Livingkids",
    "Miscarriages",
    "Abortions",
    "Medvits",
    "LivingkidsM",
    "Boys",
    "Girls",
    "MedvitsM",
    "Breastfeeding",
    "Method",
    "Prevmethod",
    "Whychart",
    "Nextpreg",
    "NextpregM",
    "Spousesame",
    "SpousesameM",
    "Timeattemptpreg",
    "BMI"
]

for col in numeric_columns:
    if col in df_clean.columns:
        df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

In [20]:
df_clean.dtypes.value_counts()

float64    68
object      7
int64       5
Name: count, dtype: int64

In [21]:
numeric_cols = df_clean.select_dtypes(include=np.number).columns
categorical_cols = df_clean.select_dtypes(exclude=np.number).columns

for col in numeric_cols:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

for col in categorical_cols:
    mode = df_clean[col].mode()
    if not mode.empty:
        df_clean[col] = df_clean[col].fillna(mode[0])

In [22]:
print("Remaining Missing Values:", df_clean.isnull().sum().sum())

Remaining Missing Values: 0

In [25]:
from src.config import PROCESSED_DATA_DIR

# Ensure directory exists
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

cleaned_data_path = PROCESSED_DATA_DIR / "cleaned_cycle_data.csv"

df_clean.to_csv(
    cleaned_data_path,
    index=False
)

print("="*50)
print("Cleaned Dataset Saved Successfully")
print("="*50)
print(f"Location : {cleaned_data_path}")
print(f"Shape    : {df_clean.shape}")

==================================================
Cleaned Dataset Saved Successfully
==================================================
Location : C:\Users\Arshia\OneDrive\Desktop\CycleSense\data\processed\cleaned_cycle_data.csv
Shape    : (1653, 80)

In [26]:
summary = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Remaining Missing Values",
        "Duplicate Rows"
    ],
    "Value": [
        df_clean.shape[0],
        df_clean.shape[1],
        df_clean.isnull().sum().sum(),
        df_clean.duplicated().sum()
    ]
})

summary

                     Metric  Value
0                      Rows   1653
1                   Columns     80
2  Remaining Missing Values      0
3            Duplicate Rows      0

In [27]:
from src.config import REPORT_DIR

# Ensure reports directory exists
REPORT_DIR.mkdir(parents=True, exist_ok=True)

summary_path = REPORT_DIR / "cleaning_summary.csv"

summary.to_csv(
    summary_path,
    index=False
)

print(f"Cleaning summary saved to:\n{summary_path}")

Cleaning summary saved to:
C:\Users\Arshia\OneDrive\Desktop\CycleSense\reports\cleaning_summary.csv

In [28]:
dtype_report = pd.DataFrame({
    "Column": df_clean.columns,
    "Data Type": df_clean.dtypes.astype(str)
})

dtype_report.head()

                                    Column Data Type
ClientID                          ClientID    object
CycleNumber                    CycleNumber     int64
Group                                Group     int64
CycleWithPeakorNot      CycleWithPeakorNot     int64
ReproductiveCategory  ReproductiveCategory     int64

In [29]:
dtype_report_path = REPORT_DIR / "data_types_after_cleaning.csv"

dtype_report.to_csv(
    dtype_report_path,
    index=False
)

print(f"Data type report saved to:\n{dtype_report_path}")

Data type report saved to:
C:\Users\Arshia\OneDrive\Desktop\CycleSense\reports\data_types_after_cleaning.csv

# Conclusions

The following preprocessing steps were completed successfully:

- Converted blank strings into missing values (`NaN`)
- Converted numeric-like object columns into numerical data types
- Imputed missing numerical values using the median
- Imputed missing categorical values using the mode
- Verified the absence of remaining missing values
- Saved the cleaned dataset and summary reports

The cleaned dataset is now ready for feature understanding and exploratory data analysis.